/*
Since there's going to be multiple people working on this (probably), I'm splitting up departments into their OWN FILES. PR CHANGES, USE MAPMERGE IF POSSIBLE.

DEPARTMENTS WILL BE PIECED TOGETHER AND THE MAP COMBINED LATER

DO NOT WORRY ABOUT WIRING AND ATMOSPHERIC PIPES. PLACE VENTS ON LAYER 1 AND SCRUBBERS ON LAYER 3. I WILL BE MAKING MAP HELPERS LATER.
*/
