#define BLOOD_SIZE_SMALL     1
#define BLOOD_SIZE_MEDIUM    2
#define BLOOD_SIZE_BIG       3
#define BLOOD_SIZE_NO_MERGE -1



#undef BLOOD_SIZE_SMALL
#undef BLOOD_SIZE_MEDIUM
#undef BLOOD_SIZE_BIG
#undef BLOOD_SIZE_NO_MERGE
