GLOBAL_LIST_INIT(bitfields, generate_bitfields())

/// Specifies a bitfield for smarter debugging
/datum/bitfield
	/// The variable name that contains the bitfield
	var/variable

	/// An associative list of the readable flag and its true value
	var/list/flags

/// Turns /datum/bitfield subtypes into a list for use in debugging
/proc/generate_bitfields()
	var/list/bitfields = list()
	for (var/_bitfield in subtypesof(/datum/bitfield))
		var/datum/bitfield/bitfield = new _bitfield
		bitfields[bitfield.variable] = bitfield.flags
	return bitfields

DEFINE_BITFIELD(admin_flags, list(
	"BUILDMODE" = R_BUILDMODE,
	"ADMIN" = R_ADMIN,
	"BAN" = R_BAN,
	"FUN" = R_FUN,
	"SERVER" = R_SERVER,
	"DEBUG" = R_DEBUG,
	"POSSESS" = R_POSSESS,
	"PERMISSIONS" = R_PERMISSIONS,
	"STEALTH" = R_STEALTH,
	"POLL" = R_POLL,
	"VAREDIT" = R_VAREDIT,
	"SOUNDS" = R_SOUNDS,
	"SPAWN" = R_SPAWN,
	"AUTOLOGIN" = R_AUTOLOGIN,
	"DBRANKS" = R_DBRANKS,
	"SENSITIVE" = R_SENSITIVE
))

DEFINE_BITFIELD(appearance_flags, list(
	"LONG_GLIDE" = LONG_GLIDE,
	"RESET_COLOR" = RESET_COLOR,
	"RESET_ALPHA" = RESET_ALPHA,
	"RESET_TRANSFORM" = RESET_TRANSFORM,
	"NO_CLIENT_COLOR" = NO_CLIENT_COLOR,
	"KEEP_TOGETHER" = KEEP_TOGETHER,
	"KEEP_APART" = KEEP_APART,
	"PLANE_MASTER" = PLANE_MASTER,
	"TILE_BOUND" = TILE_BOUND,
	"PIXEL_SCALE" = PIXEL_SCALE
))

DEFINE_BITFIELD(area_flags, list(
	"ABDUCTOR_PROOF" = ABDUCTOR_PROOF,
	"BLOBS_ALLOWED" = BLOBS_ALLOWED,
	"BLOCK_SUICIDE" = BLOCK_SUICIDE,
	// "CULT_PERMITTED" = CULT_PERMITTED,
	"FLORA_ALLOWED" = FLORA_ALLOWED,
	"HIDDEN_AREA" = HIDDEN_AREA,
	"MEGAFAUNA_SPAWN_ALLOWED" = MEGAFAUNA_SPAWN_ALLOWED,
	"MOB_SPAWN_ALLOWED" = MOB_SPAWN_ALLOWED,
	"NO_ALERTS" = NO_ALERTS,
	"NOTELEPORT" = NOTELEPORT,
	"CAVES_ALLOWED" = CAVES_ALLOWED,
	"UNIQUE_AREA" = UNIQUE_AREA,
	"VALID_TERRITORY" = VALID_TERRITORY,
	"XENOBIOLOGY_COMPATIBLE" = XENOBIOLOGY_COMPATIBLE,
	"NO_ALERTS" = NO_ALERTS,
))

// DEFINE_BITFIELD(turf_flags, list(
// 	"NO_LAVA_GEN" = NO_LAVA_GEN,
// 	"NO_RUINS" = NO_RUINS,
// 	"NOJAUNT" = NOJAUNT,
// 	"UNUSED_RESERVATION_TURF" = UNUSED_RESERVATION_TURF,
// ))

DEFINE_BITFIELD(car_traits, list(
	"CAN_KIDNAP" = CAN_KIDNAP,
))

DEFINE_BITFIELD(clothing_flags, list(
	// "ANTI_TINFOIL_MANEUVER" = ANTI_TINFOIL_MANEUVER,
	// "BLOCKS_SHOVE_KNOCKDOWN" = BLOCKS_SHOVE_KNOCKDOWN,
	// "BLOCKS_SPEECH" = BLOCKS_SPEECH,
	"BLOCK_GAS_SMOKE_EFFECT" = BLOCK_GAS_SMOKE_EFFECT,
	"LAVAPROTECT" = LAVAPROTECT,
	// "MASKINTERNALS" = MASKINTERNALS,
	"NOSLIP" = NOSLIP,
	"SCAN_REAGENTS" = SCAN_REAGENTS,
	// "SNUG_FIT" = SNUG_FIT,
	"STOPSPRESSUREDAMAGE" = STOPSPRESSUREDAMAGE,
	"THICKMATERIAL" = THICKMATERIAL,
	"VOICEBOX_DISABLED" = VOICEBOX_DISABLED,
	"VOICEBOX_TOGGLABLE" = VOICEBOX_TOGGLABLE,
	"IGNORE_HAT_TOSS" = IGNORE_HAT_TOSS, // CIT
	"ALLOWINTERNALS" = ALLOWINTERNALS,   // CIT
))

DEFINE_BITFIELD(datum_flags, list(
	"DF_ISPROCESSING" = DF_ISPROCESSING,
	"DF_VAR_EDITED" = DF_VAR_EDITED,
	"DF_USE_TAG" = DF_USE_TAG,
	// "DF_SIGNAL_ENABLED" = DF_SIGNAL_ENABLED,
))

DEFINE_BITFIELD(disease_flags, list(
	"CAN_CARRY" = CAN_CARRY,
	"CAN_RESIST" = CAN_RESIST,
	"CURABLE" = CURABLE,
))

DEFINE_BITFIELD(flags_1, list(
	"ADMIN_SPAWNED_1" = ADMIN_SPAWNED_1,
	// "ALLOW_DARK_PAINTS_1" = ALLOW_DARK_PAINTS_1,
	// "ATMOS_IS_PROCESSING_1" = ATMOS_IS_PROCESSING_1,
	"CAN_BE_DIRTY_1" = CAN_BE_DIRTY_1,
	"CONDUCT_1" = CONDUCT_1,
	"HEAR_1" = HEAR_1,
	"HOLOGRAM_1" = HOLOGRAM_1,
	"INITIALIZED_1" = INITIALIZED_1,
	// "IS_ONTOP_1" = IS_ONTOP_1,
	// "IS_SPINNING_1" = IS_SPINNING_1,
	// "NO_SCREENTIPS_1" = NO_SCREENTIPS_1,
	"NODECONSTRUCT_1" = NODECONSTRUCT_1,
	"ON_BORDER_1" = ON_BORDER_1,
	"OVERLAY_QUEUED_1" = OVERLAY_QUEUED_1,
	"PREVENT_CLICK_UNDER_1" = PREVENT_CLICK_UNDER_1,
	"PREVENT_CONTENTS_EXPLOSION_1" = PREVENT_CONTENTS_EXPLOSION_1,
	// "RAD_NO_CONTAMINATE_1" = RAD_NO_CONTAMINATE_1,
	// "RAD_PROTECT_CONTENTS_1" = RAD_PROTECT_CONTENTS_1,
	"SHOCKED_1" = SHOCKED_1,
	// "SUPERMATTER_IGNORES_1" = SUPERMATTER_IGNORES_1,
	// "UNPAINTABLE_1" = UNPAINTABLE_1,
	// cit: todo move these to tiles
	"NOJAUNT_1" = NOJAUNT_1,
	"UNUSED_RESERVATION_TURF_1" = UNUSED_RESERVATION_TURF_1,
	"DEFAULT_RICOCHET_1" = DEFAULT_RICOCHET_1,
	"NO_LAVA_GEN_1" = NO_LAVA_GEN_1,
	"NO_RUINS_1" = NO_RUINS_1,
	"BLOCK_FACE_ATOM_1" = BLOCK_FACE_ATOM_1,
))

DEFINE_BITFIELD(flags_ricochet, list(
	"RICOCHET_HARD" = RICOCHET_HARD,
	"RICOCHET_SHINY" = RICOCHET_SHINY,
))

DEFINE_BITFIELD(interaction_flags_atom, list(
	"INTERACT_ATOM_ATTACK_HAND" = INTERACT_ATOM_ATTACK_HAND,
	"INTERACT_ATOM_CHECK_GRAB" = INTERACT_ATOM_CHECK_GRAB,
	"INTERACT_ATOM_IGNORE_INCAPACITATED" = INTERACT_ATOM_IGNORE_INCAPACITATED,
	"INTERACT_ATOM_IGNORE_RESTRAINED" = INTERACT_ATOM_IGNORE_RESTRAINED,
	"INTERACT_ATOM_NO_FINGERPRINT_ATTACK_HAND" = INTERACT_ATOM_NO_FINGERPRINT_ATTACK_HAND,
	"INTERACT_ATOM_NO_FINGERPRINT_INTERACT" = INTERACT_ATOM_NO_FINGERPRINT_INTERACT,
	"INTERACT_ATOM_REQUIRES_ANCHORED" = INTERACT_ATOM_REQUIRES_ANCHORED,
	"INTERACT_ATOM_REQUIRES_DEXTERITY" = INTERACT_ATOM_REQUIRES_DEXTERITY,
	"INTERACT_ATOM_UI_INTERACT" = INTERACT_ATOM_UI_INTERACT,
))

DEFINE_BITFIELD(interaction_flags_machine, list(
	"INTERACT_MACHINE_ALLOW_SILICON" = INTERACT_MACHINE_ALLOW_SILICON,
	"INTERACT_MACHINE_OFFLINE" = INTERACT_MACHINE_OFFLINE,
	"INTERACT_MACHINE_OPEN" = INTERACT_MACHINE_OPEN,
	"INTERACT_MACHINE_OPEN_SILICON" = INTERACT_MACHINE_OPEN_SILICON,
	"INTERACT_MACHINE_REQUIRES_SIGHT" = INTERACT_MACHINE_REQUIRES_SIGHT,
	"INTERACT_MACHINE_REQUIRES_SILICON" = INTERACT_MACHINE_REQUIRES_SILICON,
	"INTERACT_MACHINE_SET_MACHINE" = INTERACT_MACHINE_SET_MACHINE,
	"INTERACT_MACHINE_WIRES_IF_OPEN" = INTERACT_MACHINE_WIRES_IF_OPEN,
))

DEFINE_BITFIELD(interaction_flags_item, list(
	"INTERACT_ITEM_ATTACK_HAND_PICKUP" = INTERACT_ITEM_ATTACK_HAND_PICKUP,
))

DEFINE_BITFIELD(item_flags, list(
	"ABSTRACT" = ABSTRACT,
	"BEING_REMOVED" = BEING_REMOVED,
	"DROPDEL" = DROPDEL,
	"EXAMINE_SKIP" = EXAMINE_SKIP,
	// "EYE_STAB" = EYE_STAB,
	"FORCE_STRING_OVERRIDE" = FORCE_STRING_OVERRIDE,
	// "HAND_ITEM" = HAND_ITEM,
	"IN_INVENTORY" = IN_INVENTORY,
	// "IN_STORAGE" = IN_STORAGE,
	"IMMUTABLE_SLOW" = IMMUTABLE_SLOW,
	"NEEDS_PERMIT" = NEEDS_PERMIT,
	"NOBLUDGEON" = NOBLUDGEON,
	"NO_MAT_REDEMPTION" = NO_MAT_REDEMPTION,
	"SLOWS_WHILE_IN_HAND" = SLOWS_WHILE_IN_HAND,
	"SURGICAL_TOOL" = SURGICAL_TOOL,
	// "XENOMORPH_HOLDABLE" = XENOMORPH_HOLDABLE,
	// "NO_PIXEL_RANDOM_DROP" = NO_PIXEL_RANDOM_DROP,
	// CIT SPECIFIC
	"ITEM_CAN_BLOCK" = ITEM_CAN_BLOCK,
	"ITEM_CAN_PARRY" = ITEM_CAN_PARRY
))

DEFINE_BITFIELD(machine_stat, list(
	"BROKEN" = BROKEN,
	"EMPED" = EMPED,
	"MAINT" = MAINT,
	"NOPOWER" = NOPOWER,
))

// DEFINE_BITFIELD(mat_container_flags, list(
// 	"MATCONTAINER_EXAMINE" = MATCONTAINER_EXAMINE,
// 	"MATCONTAINER_NO_INSERT" = MATCONTAINER_NO_INSERT,
// 	"MATCONTAINER_ANY_INTENT" = MATCONTAINER_ANY_INTENT,
// 	"MATCONTAINER_SILENT" = MATCONTAINER_SILENT,
// 	"BREAKDOWN_ALLOYS" = BREAKDOWN_ALLOYS,
// ))

// DEFINE_BITFIELD(internal_damage, list(
// 	"MECHA_INT_FIRE" = MECHA_INT_FIRE,
// 	"MECHA_INT_TEMP_CONTROL" = MECHA_INT_TEMP_CONTROL,
// 	"MECHA_INT_TANK_BREACH" = MECHA_INT_TANK_BREACH,
// 	"MECHA_INT_CONTROL_LOST" = MECHA_INT_CONTROL_LOST,
// ))

// DEFINE_BITFIELD(mecha_flags, list(
// 	"ADDING_ACCESS_POSSIBLE" = ADDING_ACCESS_POSSIBLE,
// 	"ADDING_MAINT_ACCESS_POSSIBLE" = ADDING_MAINT_ACCESS_POSSIBLE,
// 	"CANSTRAFE" = CANSTRAFE,
// 	"LIGHTS_ON" = LIGHTS_ON,
// 	"SILICON_PILOT" = SILICON_PILOT,
// 	"IS_ENCLOSED" = IS_ENCLOSED,
// 	"HAS_LIGHTS" = HAS_LIGHTS,
// ))

DEFINE_BITFIELD(mob_biotypes, list(
	"MOB_BEAST" = MOB_BEAST,
	"MOB_BUG" = MOB_BUG,
	"MOB_EPIC" = MOB_EPIC,
	"MOB_HUMANOID" = MOB_HUMANOID,
	"MOB_MINERAL" = MOB_MINERAL,
	"MOB_ORGANIC" = MOB_ORGANIC,
	"MOB_REPTILE" = MOB_REPTILE,
	"MOB_ROBOTIC" = MOB_ROBOTIC,
	"MOB_SPIRIT" = MOB_SPIRIT,
	"MOB_UNDEAD" = MOB_UNDEAD,
	// "MOB_PLANT" = MOB_PLANT
))

DEFINE_BITFIELD(mobility_flags, list(
	"MOVE" = MOBILITY_MOVE,
	"PICKUP" = MOBILITY_PICKUP,
	"PULL" = MOBILITY_PULL,
	"STAND" = MOBILITY_STAND,
	"STORAGE" = MOBILITY_STORAGE,
	"UI" = MOBILITY_UI,
	"USE" = MOBILITY_USE,
	"HOLD" = MOBILITY_HOLD,
	"RESIST" = MOBILITY_RESIST,
))

DEFINE_BITFIELD(movement_type, list(
	"FLOATING" = FLOATING,
	"FLYING" = FLYING,
	"GROUND" = GROUND,
	// "PHASING" = PHASING,
	"VENTCRAWLING" = VENTCRAWLING,
	"UNSTOPPABLE" = UNSTOPPABLE
))

DEFINE_BITFIELD(obj_flags, list(
	"BEING_SHOCKED" = BEING_SHOCKED,
	"CAN_BE_HIT" = CAN_BE_HIT,
	"DANGEROUS_POSSESSION" = DANGEROUS_POSSESSION,
	"EMAGGED" = EMAGGED,
	"FROZEN" = FROZEN,
	"IN_USE" = IN_USE,
	"ON_BLUEPRINTS" = ON_BLUEPRINTS,
	"UNIQUE_RENAME" = UNIQUE_RENAME,
	"USES_TGUI" = USES_TGUI,
	"SHOVABLE_ONTO" = SHOVABLE_ONTO,
))

DEFINE_BITFIELD(pass_flags, list(
	"LETPASSTHROW" = LETPASSTHROW,
	"PASSBLOB" = PASSBLOB,
	"PASSCLOSEDTURF" = PASSCLOSEDTURF,
	"PASSGLASS" = PASSGLASS,
	"PASSGRILLE" = PASSGRILLE,
	"PASSMOB" = PASSMOB,
	"PASSTABLE" = PASSTABLE,
))

DEFINE_BITFIELD(resistance_flags, list(
	"LAVA_PROOF" = LAVA_PROOF,
	"FIRE_PROOF" = FIRE_PROOF,
	"FLAMMABLE" = FLAMMABLE,
	"ON_FIRE" = ON_FIRE,
	"UNACIDABLE" = UNACIDABLE,
	"ACID_PROOF" = ACID_PROOF,
	"INDESTRUCTIBLE" = INDESTRUCTIBLE,
	"FREEZE_PROOF" = FREEZE_PROOF,
	// CIT SPEC.
	"GOLIATH_RESISTANCE" = GOLIATH_RESISTANCE,
	"GOLIATH_WEAKNESS" = GOLIATH_WEAKNESS
))

DEFINE_BITFIELD(sight, list(
	"BLIND" = BLIND,
	"SEE_BLACKNESS" = SEE_BLACKNESS,
	"SEE_INFRA" = SEE_INFRA,
	"SEE_MOBS" = SEE_MOBS,
	"SEE_OBJS" = SEE_OBJS,
	"SEE_PIXELS" = SEE_PIXELS,
	"SEE_SELF" = SEE_SELF,
	"SEE_THRU" = SEE_THRU,
	"SEE_TURFS" = SEE_TURFS,
))

DEFINE_BITFIELD(vis_flags, list(
	"VIS_HIDE" = VIS_HIDE,
	"VIS_INHERIT_DIR" = VIS_INHERIT_DIR,
	"VIS_INHERIT_ICON" = VIS_INHERIT_ICON,
	"VIS_INHERIT_ICON_STATE" = VIS_INHERIT_ICON_STATE,
	"VIS_INHERIT_ID" = VIS_INHERIT_ID,
	"VIS_INHERIT_LAYER" = VIS_INHERIT_LAYER,
	"VIS_INHERIT_PLANE" = VIS_INHERIT_PLANE,
	"VIS_UNDERLAY" = VIS_UNDERLAY,
))

DEFINE_BITFIELD(zap_flags, list(
	"ZAP_ALLOW_DUPLICATES" = ZAP_ALLOW_DUPLICATES,
	"ZAP_MACHINE_EXPLOSIVE" = ZAP_MACHINE_EXPLOSIVE,
	"ZAP_MOB_DAMAGE" = ZAP_MOB_DAMAGE,
	"ZAP_MOB_STUN" = ZAP_MOB_STUN,
	"ZAP_OBJ_DAMAGE" = ZAP_OBJ_DAMAGE,
	// "ZAP_GENERATES_POWER" = ZAP_GENERATES_POWER,
))

DEFINE_BITFIELD(chemical_flags, list(
	"REAGENT_DEAD_PROCESS" = REAGENT_DEAD_PROCESS,
	"REAGENT_DONOTSPLIT" = REAGENT_DONOTSPLIT,
	"REAGENT_INVISIBLE" = REAGENT_INVISIBLE,
	"REAGENT_SNEAKYNAME" = REAGENT_SNEAKYNAME,
	"REAGENT_SPLITRETAINVOL" = REAGENT_SPLITRETAINVOL,
	// "REAGENT_CAN_BE_SYNTHESIZED" = REAGENT_CAN_BE_SYNTHESIZED,
	// Cit spec.
	"REAGENT_ONLYINVERSE" = REAGENT_ONLYINVERSE,
	"REAGENT_ONMOBMERGE" = REAGENT_ONMOBMERGE,
	"REAGENT_FORCEONNEW" = REAGENT_FORCEONNEW,
))


// DEFINE_BITFIELD(reaction_flags, list(
// 	"REACTION_CLEAR_IMPURE"  = REACTION_CLEAR_IMPURE,
// 	"REACTION_CLEAR_INVERSE" = REACTION_CLEAR_INVERSE,
// 	"REACTION_CLEAR_RETAIN" = REACTION_CLEAR_RETAIN,
// 	"REACTION_INSTANT" = REACTION_INSTANT,
// 	"REACTION_HEAT_ARBITARY" = REACTION_HEAT_ARBITARY,
// 	"REACTION_COMPETITIVE" = REACTION_COMPETITIVE,
// 	"REACTION_PH_VOL_CONSTANT" = REACTION_PH_VOL_CONSTANT,
// 	"REACTION_REAL_TIME_SPLIT" = REACTION_REAL_TIME_SPLIT,
// ))

/// OLD Smoothing flags
DEFINE_BITFIELD(smooth, list(
	"SMOOTH_TRUE" = SMOOTH_TRUE,
	"SMOOTH_MORE" = SMOOTH_MORE,
	"SMOOTH_DIAGONAL" = SMOOTH_DIAGONAL,
	"SMOOTH_BORDER" = SMOOTH_BORDER,
	"SMOOTH_QUEUED" = SMOOTH_QUEUED,
))

/// OLD reagent holder flags
DEFINE_BITFIELD(reagents_holder_flags, list(
	"INJECTABLE" = INJECTABLE,
	"DRAWABLE" = DRAWABLE,
	"REFILLABLE" = REFILLABLE,
	"DRAINABLE" = DRAINABLE,
	"TRANSPARENT" = TRANSPARENT,
	"AMOUNT_VISIBLE" = AMOUNT_VISIBLE,
	"NO_REACT" = NO_REACT,
))

/// CIT rad flags
DEFINE_BITFIELD(rad_flags, list(
	"RAD_PROTECT_CONTENTS" = RAD_PROTECT_CONTENTS,
	"RAD_NO_CONTAMINATE" = RAD_NO_CONTAMINATE,
))

/// idk
DEFINE_BITFIELD(clear_conversion, list(
	"REACTION_CLEAR_IMPURE"  = REACTION_CLEAR_IMPURE,
	"REACTION_CLEAR_INVERSE" = REACTION_CLEAR_INVERSE
))

/// idk
DEFINE_BITFIELD(organ_flags, list(
	"ORGAN_SYNTHETIC" = ORGAN_SYNTHETIC,
	"ORGAN_FROZEN" = ORGAN_FROZEN,
	"ORGAN_FAILING" = ORGAN_FAILING,
	"ORGAN_EXTERNAL" = ORGAN_EXTERNAL,
	"ORGAN_VITAL" = ORGAN_VITAL,
	"ORGAN_NO_SPOIL" = ORGAN_NO_SPOIL,
))

DEFINE_BITFIELD(genital_flags, list(
	"GENITAL_BLACKLISTED" = GENITAL_BLACKLISTED,
	"GENITAL_INTERNAL" = GENITAL_INTERNAL,
	"GENITAL_HIDDEN" = GENITAL_HIDDEN,
	"GENITAL_THROUGH_CLOTHES" = GENITAL_THROUGH_CLOTHES,
	"GENITAL_FUID_PRODUCTION" = GENITAL_FUID_PRODUCTION,
	"CAN_MASTURBATE_WITH" = CAN_MASTURBATE_WITH,
	"MASTURBATE_LINKED_ORGAN" = MASTURBATE_LINKED_ORGAN,
	"CAN_CLIMAX_WITH" = CAN_CLIMAX_WITH,
))

/// Cit combat mode
DEFINE_BITFIELD(combat_flags, list(
	"COMBAT_FLAG_SPRINT_TOGGLED" = COMBAT_FLAG_SPRINT_TOGGLED,
	"COMBAT_FLAG_SPRINT_ACTIVE" = COMBAT_FLAG_SPRINT_ACTIVE,
	"COMBAT_FLAG_ATTEMPTING_CRAWL" = COMBAT_FLAG_ATTEMPTING_CRAWL,
	"COMBAT_FLAG_HARD_STAMCRIT" = COMBAT_FLAG_HARD_STAMCRIT,
	"COMBAT_FLAG_INTENTIONALLY_RESTING" = COMBAT_FLAG_INTENTIONALLY_RESTING,
	"COMBAT_FLAG_RESISTING_REST" = COMBAT_FLAG_RESISTING_REST,
	"COMBAT_FLAG_SPRINT_FORCED" = COMBAT_FLAG_SPRINT_FORCED
))

/// Cit specific. For parrying
DEFINE_BITFIELD(shield_flags, list(
	"SHIELD_TRANSPARENT" = SHIELD_TRANSPARENT,
	"SHIELD_ENERGY_WEAK" = SHIELD_ENERGY_WEAK,
	"SHIELD_KINETIC_WEAK" = SHIELD_KINETIC_WEAK,
	"SHIELD_KINETIC_STRONG" = SHIELD_KINETIC_STRONG,
	"SHIELD_ENERGY_STRONG" = SHIELD_ENERGY_STRONG,
	"SHIELD_DISABLER_DISRUPTED" = SHIELD_DISABLER_DISRUPTED,
	"SHIELD_NO_RANGED" = SHIELD_NO_RANGED,
	"SHIELD_NO_MELEE" = SHIELD_NO_MELEE,
	"SHIELD_CAN_BASH" = SHIELD_CAN_BASH,
	"SHIELD_BASH_WALL_KNOCKDOWN" = SHIELD_BASH_WALL_KNOCKDOWN,
	"SHIELD_BASH_ALWAYS_KNOCKDOWN" = SHIELD_BASH_ALWAYS_KNOCKDOWN,
	"SHIELD_BASH_WALL_DISARM" = SHIELD_BASH_WALL_DISARM,
	"SHIELD_BASH_ALWAYS_DISARM" = SHIELD_BASH_ALWAYS_DISARM,
	"SHIELD_BASH_GROUND_SLAM" = SHIELD_BASH_GROUND_SLAM,
	"SHIELD_BASH_GROUND_SLAM_DISARM" = SHIELD_BASH_GROUND_SLAM_DISARM,
))

/// idk
DEFINE_BITFIELD(storage_flags, list(
	"STORAGE_LIMIT_MAX_ITEMS" = STORAGE_LIMIT_MAX_ITEMS,
	"STORAGE_LIMIT_MAX_W_CLASS" = STORAGE_LIMIT_MAX_W_CLASS,
	"STORAGE_LIMIT_COMBINED_W_CLASS" = STORAGE_LIMIT_COMBINED_W_CLASS,
	"STORAGE_LIMIT_VOLUME" = STORAGE_LIMIT_VOLUME,
))

/// Species thingy
DEFINE_BITFIELD(mutantrace_variation, list(
	"STYLE_DIGITIGRADE" = STYLE_DIGITIGRADE,
	"STYLE_MUZZLE" = STYLE_MUZZLE,
	"STYLE_SNEK_TAURIC" = STYLE_SNEK_TAURIC,
	"STYLE_PAW_TAURIC" = STYLE_PAW_TAURIC,
	"STYLE_HOOF_TAURIC" = STYLE_HOOF_TAURIC,
	"STYLE_NO_ANTHRO_ICON" = STYLE_NO_ANTHRO_ICON,
	"USE_SNEK_CLIP_MASK" = USE_SNEK_CLIP_MASK,
	"USE_QUADRUPED_CLIP_MASK" = USE_QUADRUPED_CLIP_MASK,
))
