language: generic
dist: xenial
sudo: false

branches:
  except:
  - ___TGS3TempBranch
  - ___TGSTempBranch

matrix:
  include:
    - name: "Run Linters"
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - tools/travis/install_build_tools.sh
        - tools/travis/install_dreamchecker.sh
      script:
        - tools/travis/check_filedirs.sh tgstation.dme
        - tools/travis/check_changelogs.sh
        - find . -name "*.php" -print0 | xargs -0 -n1 php -l
        - find . -name "*.json" -not -path "./tgui/node_modules/*" -print0 | xargs -0 python3 ./tools/json_verifier.py
        - tools/travis/build_tgui.sh
        - tools/travis/check_grep.sh
        - python3 tools/travis/check_line_endings.py
        - ~/dreamchecker

    - name: "Compile All Maps"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
      before_script:
        - tools/travis/template_dm_generator.py
      script:
        - tools/travis/dm.sh -DTRAVISBUILDING -DTRAVISTESTING -DALL_MAPS tgstation.dme

    - name: "Compile and Run Tests"
      addons:
        mariadb: '10.2'
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6:i386
            - gcc-multilib
            - g++-7
            - g++-7-multilib
            - libmariadb-client-lgpl-dev:i386
            - libmariadbd-dev
      cache:
        directories:
          - $HOME/BYOND
          - $HOME/libmariadb
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
        - tools/travis/install_libmariadb.sh
        - tools/travis/install_rust_g.sh
      before_script:
        - mysql -u root -e 'CREATE DATABASE tg_travis;'
        - mysql -u root tg_travis < SQL/tgstation_schema.sql
        - mysql -u root -e 'CREATE DATABASE tg_travis_prefixed;'
        - mysql -u root tg_travis_prefixed < SQL/tgstation_schema_prefixed.sql
        - tools/travis/build_bsql.sh
      script:
        - tools/travis/dm.sh -DTRAVISBUILDING tgstation.dme || travis_terminate 1
        - tools/travis/run_server.sh
