language: generic
sudo: false
branches:
  except:
  - ___TGS3TempBranch
env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1418"
    - NODE_VERSION="4"
    - RUST_G_VERSION="0.2.0"
    - BUILD_TOOLS=false
    - BUILD_TESTING=false
    - DM_MAPFILE="loadallmaps"
    matrix:
    - BUILD_TOOLS=true
    - BUILD_TESTING=true
    - BUILD_TESTING=false

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
    - tgui/node_modules
    - $HOME/.rustup
    - $HOME/.cargo


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - gcc-multilib
      - python3
      - python3-pip

install:
  - tools/travis/install_build_tools.sh

before_script:
  - tools/travis/before_build_tools.sh
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_tools.sh
  - tools/travis/build_dependencies.sh
  - tools/travis/build_byond.sh

