language: generic
dist: xenial
sudo: false

branches:
  except:
  - ___TGS3TempBranch
  - ___TGSTempBranch

matrix:
  include:
    - name: "Run Linters"
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - tools/travis/install_build_tools.sh
      script:
        - tools/travis/check_filedirs.sh tgstation.dme
        - tools/travis/build_tools.sh
        - tools/travis/lint_grep.sh

    - name: "Compile All Maps"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
      before_script:
        - tools/travis/template_dm_generator.py
      script:
        - tools/travis/dm.sh -DTRAVISBUILDING -DTRAVISTESTING -DALL_MAPS tgstation.dme

    - name: "Compile and Run Tests"
      addons:
        mariadb: '10.2'
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6:i386
            - libssl-dev:i386
            - gcc-multilib
            - g++-7
            - g++-7-multilib
            - libmariadb-client-lgpl-dev:i386
            - libmariadbd-dev
      cache:
        directories:
          - $HOME/.cargo
          - $HOME/.rustup
          - $HOME/BYOND
          - $HOME/libmariadb
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
        - tools/travis/install_libmariadb.sh
        - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-host i686-unknown-linux-gnu
        - source ~/.cargo/env
      before_script:
        - mysql -u root -e 'CREATE DATABASE tg_travis;'
        - mysql -u root tg_travis < SQL/tgstation_schema.sql
        - mysql -u root -e 'CREATE DATABASE tg_travis_prefixed;'
        - mysql -u root tg_travis_prefixed < SQL/tgstation_schema_prefixed.sql
        - tools/travis/build_rust_g.sh
        - tools/travis/build_bsql.sh
      script:
        - tools/travis/dm.sh -DTRAVISBUILDING tgstation.dme || travis_terminate 1
        - tools/travis/run_server.sh
