pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
artifacts:
- path: TGS3.zip
  name: TGS3
- path: MD5-SHA1.txt
  name: MD5SHA1
install:
  - choco install fciv
before_build:
  - nuget restore tools/tgstation-server-3/TGStationServer3.sln
build:
  project: tools/tgstation-server-3/TGStationServer3.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: "tools/appveyor/TGS3Release.ps1"
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "\[TGSDeploy\]"){$env:TGSDeploy = "Do it."}
  - ps: $env:TGSVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$env:APPVEYOR_BUILD_FOLDER/tools/tgstation-server-3/TGServerService/bin/Release/TGServerService.exe").FileVersion
deploy:
  release: "tgstation-server-v$(TGSVersion)"
  description: 'The /tg/station server suite'
  provider: GitHub
  auth_token:
    secure: 9Yf+FtoE7nf36V3dyVRANkNZ7og4dp/0uojCS51vrvIeNOTIM8Nq24lylgVBOhSL
  artifact: TGS3,MD5SHA1
  draft: false
  prerelease: false
  on:
    TGSDeploy: "Do it."
