#define ROCKPAPERSCISSORS_RANGE				3
#define ROCKPAPERSCISSORS_TIME_LIMIT		20 SECONDS

#define ROCKPAPERSCISSORS_LOSE				"lose"
#define ROCKPAPERSCISSORS_WIN				"win"
#define ROCKPAPERSCISSORS_TIE				"tie"
#define ROCKPAPERSCISSORS_NOT_DECIDED		"not_decided"
