
#ifndef PLAYERPOLL_EXTERNAL_CONFIGURATION
#warn "PLAYER POLL MODULE NOT CONFIGURED"
#endif

/*
#define PLAYERPOLL_EXTERNAL_CONFIGURATION
#define PLAYERPOLL_PROTECT_DATUM(path)
#define PLAYERPOLL_NEW_QUERY(text)
#define PLAYERPOLL_EXECUTE_QUERY(query)
#define PLAYERPOLL_QUERY_NEXTROW(query)
#define PLAYERPOLL_QUERY_GETITEM(query, index)
#define PLAYERPOLL_FORMAT_TABLE_NAME(name)
*/
