//Halloween Fluff Papers!

/obj/item/paper/fluff/balls/spookyasylum/memo/cookmemo
	name = "Memo: Cooks"
	info = "If you're reading this, thank you for volunteering your culinary services! Not only are you helping to keep costs down by rendering bluespace catering unnecessary, but you're also helping to give this event an 'organic' touch!<br>This isn't your typical day on the job, so be sure to focus on quality, not quantity. People are expecting better food than normal, and we've given you higher-quality cuts than usual to work with. Ideally you'll have botany to help with produce - if not, we may be able to deliver you some.<br>Remember to account for crew dietary concerns and provide those with less flexible digestive systems with more than one option if possible. Lastly, be sure to avoid foods that are particularly dangerous, we aren't looking for meals to \"die for\"<br>-Generated by Organic Resources Department Bot #7004"

/obj/item/paper/fluff/balls/spookyasylum/memo/botanymemo
	name = "Memo: Botanists"
	info = "If you're reading this, thank you for lending us your \"green thumbs\"! Provided a cook is on duty, you'll save us the trouble of bluespace shipping produce, as well as giving us the privilege of saying it was \"locally sourced\"! If there isn't a chef...we may be able to put what you grow to good use yet.<br>Remember, your primary goal here is to produce produce. Not cannabis, not tomatoes that mutate people, we want things people can safely eat. Do what you can for the cook if there is one - otherwise, aspire for variety.<br>-Generated by Organic Resources Department Bot #7004"

/obj/item/paper/fluff/balls/spookyasylum/memo/janniememo
	name = "Memo: Janitors"
	info = "If you're reading this, thanks for volunteering your janitorial services! You're greatly appreciated today, as this event will likely remind you why Citadel custodians command a higher salary than their counterparts in other sectors.<br>On the bright side, you shouldn't expect much in the way of danger.<br>-Generated by Organic Resources Department Bot #7004"

/obj/item/paper/fluff/balls/spookyasylum/memo/securitymemo
	name = "Security Debrief"
	info = "<b>Greetings Security Officers,</b><br>Whether you've chosen or been chosen to help oversee this event, we appreciate your service today. Although this may come as a disappointment to some of you, we can absolutely confirm a lack of credible threats for once. As such, your primary mission is to keep the peace.<br>Central Command understands this may be difficult for those of you from military backgrounds - fortunately, we intend to be far more accessible for the sake of this event. Feel free to contact us if you have any uncertainties how to handle a situation, as cost is not the concern it normally is. However, you're expected to follow any orders we give to the best of your ability.<br>Some other things you should be aware of:<br>- You may see civilians in security apparel - this is to be expected as \"shitsec\" costumes are trending on the NTnet. For this reason we have issued you special uniforms. If you see a partygoer in THOSE, THEN you may have reason for concern.<br>- Items that may normally be cause for alarm can generally be assumed to be toys and/or replicas, potentially as part of a costume. You'll be informed whether an item is to be of concern, as Central Command will be handling much of the surveillance work.<br>- Speaking of surveillance, the chapel and larger building to the east are not equipped with cameras. The chapel has been fully investigated by an Inquistion, but due to \[REDACTED] they were unable to do the same for the east compound. You are not responsible for what goes on in these areas and partygoers have been warned to enter at their own risk.<br>-Central Command"

/obj/item/paper/fluff/balls/spookyasylum/diary/diary01
	name = "7/31/2559"
	info = "People who say they can't afford any more than a nanoapartment really need to broaden their horizons. You'd be amazed by what you can find if you're willing to put up with a longer commute! I mean look at me, I got a place with square footage that'd put First Victorians to shame!<br>Part of why this place was so cheap was because some \"terrible things\" happened here in the past, apparently. Still, what's in the past is in the past, is it not?"

/obj/item/paper/fluff/balls/spookyasylum/diary/diary02
	name = "8/2/2559"
	info = "Nice as this place is, it's kind of lonely. It also might be a bit tough to maintain all by myself, so what if I made it a hotel? Something like this'd surely stand out, especially when most of the hotels around here are Twin Nexuses.<br>It's not that they're not nice places - it's just that when you've been to one, you've been to them all. A hotel here? It'd be one of a kind!"

/obj/item/paper/fluff/balls/spookyasylum/diary/diary03
	name = "9/13/2559"
	info = "<center>All hell has broken loose.</center><br>In the early evening, hundreds, maybe thousands of ghosts burst out of the chapel and old medical wing. They rushed through the halls, breaking any lights they passed. Then it happened.<br>We had quite a few doctors present that night, and suddenly they all went insane. One barged into the kitchen and dove headfirst into the gibber. The rest charged into medbay, each seeming to choose a unique method of suicide. Lethal injections, the electric chair, self-lobotomy - each seemed to top the last in absurdity. Then the ghosts all converged back in the chapel, appearing to vanish as quickly as they arrived.<br>All my remaining guests and staff have fled. Everyone seemed to have somewhere they could go...except for me. I can only pray these spirits don't take me in my sleep..."

/obj/item/paper/fluff/balls/spookyasylum/diary/diary04
	name = "9/16/2559"
	info = "Word travels a lot faster than I thought, I haven't seen a customer in days...<br>The good news is that whatever happened a few days hasn't repeated itself. It's just me here - any staff I had resigned immediately after what went down on the 13th. I'm sure I could handle a few guests but am I gonna see one anytime soon?"

/obj/item/paper/fluff/balls/spookyasylum/diary/diary05
	name = "10/7/2559"
	info = "Finally, I'm free of this nightmare.<br>Some folks showed up for the first time in weeks, said they were a part of \"NanoTransen\" or something. They seemed shocked I haven't heard of them, but all I care about is the fact they were willing to buy this place. I figured I'd at least get what I invested at this place, but for a \"megacorporation\" they sure seemed like a bunch of tightwads. Still, I took their offer.<br>It's their problem now."

/obj/item/paper/fluff/balls/spookyasylum/cell03
	name = "Cell 3 Patient Information"
	info = "<b>Name:</b> J. Crane<br><b>Age:</b> 46 <b>Gender:</b> M <b>Height:</b> 183cm <b>Weight:</b> 81kg<br><b>Notes:</b> Patient exhibits violent tendencies and is not to be released from restraints under any circumstances. To reduce risk of violent outbreaks, birds; which patient has a strong phobia towards; are no longer allowed in proximity of cells, this includes the chief of staff's pet parrot."

/obj/item/paper/fluff/balls/spookyasylum/cell04
	name = "Cell 4 Patient Information"
	info = "<b>Name:</b> Fidel S.<br><b>Age:</b> 20 <b>Gender:</b> M <b>Height:</b> 170cm <b>Weight:</b> 68kg<br><b>Notes:</b> Patient appears to be under the delusion that he is a dog, suffers from incontinence, and bites staff. Patient to be kept restrained in cell after attacking orderly Robinson, do not remove patient's muzzle outside designated meal periods."

/obj/item/paper/fluff/balls/spookyasylum/traffickingvictim
	name = "Cell 1 Patient Information"
	info = "<b>Name:</b> S. Albright<br><b>Age:</b> 26 <b>Gender:</b> F <b>Height:</b> 174cm <b>Weight:</b> 63kg<br><b>Notes:</b> \[The notes are crossed out and unreadable, but there is writing on the back of the paper] Buyer found in Sol system, wealthy Martian man looking for a cheap bride, doesn't mind poor condition of the merchandise. Will be packaging with the next supply ship for transport."

/obj/item/paper/fluff/balls/spookyasylum/healstaffnote
    name = "Shipping Manifest 'Healing Staves'"
    info = "Contained in this chest are several magical healing staves created by NT sanctioned warlocks, please use them in the event an employee is injured during the festivities. We hope you have a safe and enjoyable celebration, remember you are expected to return to work promptly at its conclusion.<br>We apologize in the unlikely event the contents of the crate are scattered around the asylum by its teleportation."

//Dorm Buttons

/obj/machinery/button/door/dorms/dorm01
    name = "dorm 1 button"
    id = "D100"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm02
    name = "dorm 2 button"
    id = "D101"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm03
    name = "dorm 3 button"
    id = "D102"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm04
    name = "dorm 4 button"
    id = "D103"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm05
    name = "dorm 5 button"
    id = "D104"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm06
    name = "dorm 6 button"
    id = "D105"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm07
    name = "dorm 7 button"
    id = "D106"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm08
    name = "dorm 8 button"
    id = "D107"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm09
    name = "dorm 9 button"
    id = "D108"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm10
    name = "dorm 10 button"
    id = "D109"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm11
    name = "dorm 11 button"
    id = "D110"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm12
    name = "dorm 12 button"
    id = "D111"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm13
    name = "dorm 13 button"
    id = "D112"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm14
    name = "dorm 14 button"
    id = "D113"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm15
    name = "dorm 15 button"
    id = "D114"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm16
    name = "dorm 16 button"
    id = "D115"
    normaldoorcontrol = 1
    pixel_x = 24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm17
    name = "dorm 17 button"
    id = "D116"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm18
    name = "dorm 18 button"
    id = "D117"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm19
    name = "dorm 19 button"
    id = "D118"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/dorm20
    name = "dorm 20 button"
    id = "D119"
    normaldoorcontrol = 1
    pixel_x = -24
    specialfunctions = 4

/obj/machinery/button/door/dorms/patient1
    name = "door bolt"
    id = "D120"
    normaldoorcontrol = 1
    pixel_x = 24
    pixel_y = -8
    specialfunctions = 4

/obj/machinery/button/door/dorms/patient2
    name = "door bolt"
    id = "D121"
    normaldoorcontrol = 1
    pixel_x = 24
    pixel_y = -8
    specialfunctions = 4

/obj/machinery/button/door/dorms/luxury1
    name = "Privacy Shutter Control"
    id = "L00"
    pixel_x = -8
    pixel_y = -24

/obj/machinery/button/door/dorms/luxury2
    name = "Privacy Shutter Control"
    id = "L01"
    pixel_x = 8
    pixel_y = -24

/obj/machinery/button/door/dorms/luxury3
    name = "Privacy Shutter Control"
    id = "L02"
    pixel_x = 8
    pixel_y = 24

/obj/machinery/button/door/dorms/luxury4
    name = "Privacy Shutter Control"
    id = "L03"
    pixel_x = -24
    pixel_y = 8

//Dorm Doors

/obj/machinery/door/airlock/wood/dorms/dorm01
	name = "Room 1"
	id_tag = "D100"

/obj/machinery/door/airlock/wood/dorms/dorm02
	name = "Room 2"
	id_tag = "D101"

/obj/machinery/door/airlock/wood/dorms/dorm03
	name = "Room 3"
	id_tag = "D102"

/obj/machinery/door/airlock/wood/dorms/dorm04
	name = "Room 4"
	id_tag = "D103"

/obj/machinery/door/airlock/wood/dorms/dorm05
	name = "Room 5"
	id_tag = "D104"

/obj/machinery/door/airlock/wood/dorms/dorm06
	name = "Room 6"
	id_tag = "D105"

/obj/machinery/door/airlock/wood/dorms/dorm07
	name = "Room 7"
	id_tag = "D106"

/obj/machinery/door/airlock/wood/dorms/dorm08
	name = "Room 8"
	id_tag = "D107"

/obj/machinery/door/airlock/wood/dorms/dorm09
	name = "Room 9"
	id_tag = "D108"

/obj/machinery/door/airlock/wood/dorms/dorm10
	name = "Room 10"
	id_tag = "D109"

/obj/machinery/door/airlock/wood/dorms/dorm11
	name = "Room 11"
	id_tag = "D110"

/obj/machinery/door/airlock/wood/dorms/dorm12
	name = "Room 12"
	id_tag = "D111"

/obj/machinery/door/airlock/wood/dorms/dorm13
	name = "Room 13"
	id_tag = "D112"

/obj/machinery/door/airlock/wood/dorms/dorm14
	name = "Room 14"
	id_tag = "D113"

/obj/machinery/door/airlock/wood/dorms/dorm15
	name = "Room 15"
	id_tag = "D114"

/obj/machinery/door/airlock/wood/dorms/dorm16
	name = "Room 16"
	id_tag = "D115"

/obj/machinery/door/airlock/wood/dorms/dorm17
	name = "Room 17"
	id_tag = "D116"

/obj/machinery/door/airlock/wood/dorms/dorm18
	name = "Room 18"
	id_tag = "D117"

/obj/machinery/door/airlock/wood/dorms/dorm19
	name = "Room 19"
	id_tag = "D118"

/obj/machinery/door/airlock/wood/dorms/dorm20
	name = "Room 20"
	id_tag = "D119"

/obj/machinery/door/airlock/wood/dorms/patient1
	name = "Recovery Room 1"
	id_tag = "D120"

/obj/machinery/door/airlock/wood/dorms/patient2
	name = "Recovery Room 2"
	id_tag = "D121"

//Luxury Dorm Shutters

/obj/machinery/door/poddoor/shutters/preopen/luxury_dorms/luxury01
	name = "Luxury Dorm 1"
	id = "L00"

/obj/machinery/door/poddoor/shutters/preopen/luxury_dorms/luxury02
	name = "Luxury Dorm 2"
	id = "L01"

/obj/machinery/door/poddoor/shutters/preopen/luxury_dorms/luxury03
	name = "Luxury Dorm 3"
	id = "L02"

/obj/machinery/door/poddoor/shutters/preopen/luxury_dorms/luxury04
	name = "Luxury Dorm 4"
	id = "L03"

//This is just so I don't have to mass varedit!

/obj/structure/falsewall/halloweenBall/wood
	name = "wooden wall"
	desc = "A wall with wooden plating. Stiff."
	icon = 'icons/turf/walls/wood_wall.dmi'
	icon_state = "wood"
	mineral = /obj/item/stack/sheet/mineral/wood
	walltype = /turf/closed/wall/mineral/wood
	canSmoothWith = list(/obj/structure/falsewall/wood, /turf/closed/wall/mineral/wood, /turf/closed/indestructible/wood)
