/datum/reagent/toxin/plasma/on_mob_life(mob/living/M)
	if(ishuman(M))
		var/mob/living/carbon/human/H = M
		switch(rand(1,14))
			if(1)
				H.dna.features["mcolor"] = random_short_color()
			if(2)
				H.dna.features["mcolor2"] = random_short_color()
			if(3)
				H.dna.features["mcolor3"] = random_short_color()
			if(4)
				H.dna.features["tail_lizard"] = pick(GLOB.tails_list_lizard)
			if(5)
				H.dna.features["snout"] = pick(GLOB.snouts_list)
			if(6)
				H.dna.features["horns"] = pick(GLOB.horns_list)
			if(7)
				H.dna.features["frills"] = pick(GLOB.frills_list)
			if(8)
				H.dna.features["spines"] = pick(GLOB.spines_list)
			if(9)
				H.dna.features["body_markings"] = pick(GLOB.body_markings_list)
			if(10)
				H.dna.features["moth_wings"] = pick(GLOB.moth_wings_list)
			if(11)
				H.dna.features["mam_body_markings"] = pick(GLOB.mam_body_markings_list)
			if(12)
				H.dna.features["mam_ears"] = pick(GLOB.mam_ears_list)
			if(13)
				H.dna.features["mam_tail"] = pick(GLOB.mam_tails_list)
			if(14)
				H.dna.features["taur"] = pick(GLOB.taur_list)
		H.update_body()
		H.update_hair()
		H.update_body_parts()
	. = ..()
